// draw update, enter and exit selections of selectionObject
function selectionDiagram(drawselector, subjectSelection) {
    // collect the selectionObject information
    let nodemap = (sel, label) => sel.nodes().map(
        n => ({ tag: n.tagName, val: n.__data__, status: label }))
    let subjectData = nodemap(subjectSelection, 'update')
    subjectData.push(...nodemap(subjectSelection.enter(), 'enter'))
    subjectData.push(...nodemap(subjectSelection.exit(), 'exit'))

    let svg = d3.select(drawselector)
    svg.append("text")
        .text("DOM Elements")
        .attr("y", 15)
        .style("font-weight", "bold")
    svg.append("text")
        .text("Data")
        .attr("y", 15)
        .attr("x", 310)
        .style("font-weight", "bold")

    let groups = svg.selectAll(".seldraw")
        .data(subjectData)
        .enter()
        .append("g")
        .attr("class", "seldraw")
        .attr("transform", (d, i) => `translate(10,${30 + i * 30})`)
    groups.append('rect')
        .attr("height", "20")
        .attr("width", "70")
        .style("stroke", "grey")
        .style("stroke-width", "3")
        .style("fill", "none")
        .style("display", d => d.status === 'enter' ? 'none' : 'block')
    groups.append("text")
        .text((d, i) => `${i} <${d.tag}>`)
        .attr("fill", "blue")
        .attr("y", 15)
        .attr("x", 5)
        .style("text-decoration", d => d.status === "exit" ? 'line-through' : 'none')
        .style("display", d => d.status === 'enter' ? 'none' : 'block')
    groups.append("line")
        .attr("x1", 80)
        .attr("y1", 10)
        .attr("x2", 280)
        .attr("y2", 10)
        .attr("stroke", "black")
    groups.append("text")
        .text((d, i) => d.status)
        .attr("fill", "red")
        .attr("y", 12)
        .attr("x", 180 - 35)
    groups.append("text")
        .text((d, i) => `${i}: ${d.val}`)
        .attr("fill", "grey")
        .attr("y", 15)
        .attr("x", 290)
        .style("text-decoration", d => d.status === "exit" ? 'line-through' : 'none')
}
